name: Create Release
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Set the git username and email automatically
        uses: fregante/setup-git-user@v2

      - name: Get version
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Get latest release
        id: get_latest_release
        uses: actions/github-script@v5
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return releases.data[0].tag_name;

      - name: Check if version has changed
        continue-on-error: true
        run: |
          if [ "${{ steps.get_version.outputs.VERSION }}" = "${{ steps.get_latest_release.outputs.result }}" ]; then
            echo "::warning::Version has not changed, skipping subsequent steps..."
            exit 1
          fi

      - name: Install zip
        if: ${{ job.status == 'success' }}
        run: sudo apt-get install zip

      - name: Zip src directory
        if: ${{ job.status == 'success' }}
        run: |
          cd src
          zip -r ../it.francescoface.PawExtensions.1password-connect.zip .

      - name: Create Git tag
        if: ${{ job.status == 'success' }}
        run: git tag ${{ steps.get_version.outputs.VERSION }}

      - name: Push Git tags
        if: ${{ job.status == 'success' }}
        run: git push origin --tags

      - name: Create Release
        if: ${{ job.status == 'success' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: ${{ job.status == 'success' }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./it.francescoface.PawExtensions.1password-connect.zip
          asset_name: it.francescoface.PawExtensions.1password-connect.zip
          asset_content_type: application/zip